Pull (cherry-pick) head changeset from [ci/patch-devel-gettext-lib-blnk-incdirs]
Original Changelog Message:
devel/gettext-lib: Patch buidlink3.mk for INCDIRS matching pkg install

* devel/gettext-lib: Patch buidlink3.mk to use - when not USE_BUILTIN -
  BUILDLINK_INCDIRS.gettext with a pathname matching the gettext-lib
  pkg install.

This may serve to prevent a build failure, such as illustrated in the
following, in an excerpt from a local build under devel/gettext-tools

~~~~
[sic]
--- localcharset.o ---
/usr/pkg/libexec/ccache/clang -DHAVE_CONFIG_H -DEXEEXT=\"\" -I. -I..  -I../intl -I../intl  -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1   -I/usr/pkg/include -D_XOPEN_SOURCE_EXTENDED=1 -I/usr/pkg/include/ncurses -D_THREAD_SAFE  -Wl,--as-needed -O2 -Wno-error=unused-command-line-argument -fno-stack-protector -Wl,-L/usr/pkg/lib -I/usr/pkg/include -D_XOPEN_SOURCE_EXTENDED=1 -I/usr/pkg/include/ncurses -c -o localcharset.o localcharset.c
--- closeout.o ---
In file included from closeout.c:28:
./gettext.h:26:11: fatal error: 'libintl.h' file not found
          ^~~~~~~~~~~
1 error generated.
*** [closeout.o] Error code 1

bmake[6]: stopped in /usr/pkgsrc/devel/gettext-tools/work.riparian.pkg/gettext-0.20.1/gettext-runtime/gnulib-lib
[sic]
~~~~

This build was produced in an environment in which the following build
parameters are assumed:
* IS_BUILTIN.gettext = no
* USE_BUILTIN.gettext = no
* PREFER.gettext = pkgsrc

The patched build has been tested with a local pkgsrc installation under
FreeBSD 12.1, using clang from LLVM 9 in FreeBSD ports

(cherry picked from commit e8e259640785e11222927300b7d625d8692b110c)