devel/gobject-introspection: Add patches for using pkgsrc gettext with gir
Under a build configuration using pkgsrc cwrappers and pkgsrc
gettext-lib on a FreeBSD build host, the following build error was
occurring

~~~~
FAILED: gir/GLib-2.0.gir
/usr/pkg/bin/python3.7 tools/g-ir-scanner [sic]
In file included from /usr/pkgsrc/devel/gobject-introspection/work/[sic]
/usr/pkg/include/glib-2.0/glib/gi18n.h:23:10: fatal error: 'libintl.h'
file not found
         ^~~~~~~~~~~
1 error generated.
Traceback (most recent call last): [sic]
distutils.errors.DistutilsExecError: command '/usr/bin/clang-cpp' failed
with exit status 1
~~~~

This changeset adds a source patch and a corresponding subst class for
devel/gobject-introspection, such that should serve to ensure that the
pkgsrc libintl.h can be located by gir during the pkg build, in build
configurations using pkgsrc gettext-lib

(cherry picked from commit 37e0941f26b3de4a017e9859171aee9d7b023ab7)